export default {
  QUESTION_RECEIVED: "QUESTION_RECEIVED",
  FETCHING: "FETCHING",
  FETCHED: "FETCHED",
  SETLOADING: "SETLOADING",
  HIDEBUBBLETIP: "HIDEBUBBLETIP",
  SETBUBBLETYPE: "SETBUBBLETYPE",
  REPORT: "REPORT"
};